FROM debian:bullseye
WORKDIR /app

RUN apt update \
    && apt-get dist-upgrade -y

RUN apt install -y curl\
    tor\
    privoxy\
    procps\
    systemctl\
    iproute2\
    git\
    iptables\
    sudo
