FROM debian:bullseye
WORKDIR /app

RUN apt update \
    && apt-get dist-upgrade -y

RUN apt install -y curl\
    nano\
    netcat\
    tor\
    privoxy\
    procps\
    systemd\
    systemctl\
    iproute2\
    net-tools\
    git\
    iptables\
    sudo
