#!/bin/bash
# Import parameter.
param=$1
# Tops two options --version and --help,
# showing torcontroller Current version and features.
if [[ "$param" == "--version" || "$param" == "-V" ]]; then
    echo "------torcontroller-1.0------"
elif [[ "$param" == "--help" || "$param" == "-H" ]]; then
    echo "Usage: torcontroller [OPTIONS]"
    echo ""
    echo "Option    Long Option         Meaning"
    echo "-A        --resetpassword     Reset Tor authentication key."
    echo "-C        --stop              Stop tor and privoxy service."
    echo "-G        --getip             Shows current IP address."
    echo "-S        --start             Start tor and privoxy service."
    echo "-H        --help              Show this help text and exit."
    echo "-V        --version           Print current version and exit."
    echo "-W        --switch            Change IP. Switch Tor though another router service."
    exit 0
elif [[ "$param" == "--start" || "$param" == "-S" ]]; then
    bash ../lib/torcontroller/startTorcontrol.sh &&
        echo "Command succeeded." &&
        exit 0
elif [[ "$param" == "--stop" || "$param" == "-C" ]]; then
    bash ../lib/torcontroller/stopTorcontrol.sh &&
        echo "Command succeeded." &&
        exit 0
elif [[ "$param" == "--resetpassword" || "$param" == "-A" ]]; then
    bash ../lib/torcontroller/resetTorPassword.sh &&
        echo "Command succeeded." &&
        exit 0
elif [[ "$param" == "--switch" || "$param" == "-W" ]]; then
    bash ../lib/torcontroller/switchTorRouter.sh &&
        echo "Command succeeded." &&
        exit 0
elif [[ "$param" == "--getip" || "$param" == "-G" ]]; then
    bash ../lib/torcontroller/getIP.sh &&
        echo "Command succeeded." &&
        exit 0
else
    echo "torcontroller [OPTION] is necessary."
    echo "Command 'torcontroller --help' to read options."
    echo 1
fi
