#!/bin/sh
# If any error, exit. Fix in future
# set -xe

echo "torcontroller postinst setting script..."
# Place systemctl setting file.
# The current version of torcontroller relies on systemctl to launch the tor and privoxy services.
if [ -f /etc/systemd/system/privoxy.service ]; then
    echo "User-defined privoxy service found. Leaving existing file untouched."
    echo "A new version of the configuration file is available: /etc/systemd/system/privoxy.service.dpkg-new"
    echo "Please review and merge it into your existing configuration if necessary."
    cp /usr/share/torcontroller/defaults/privoxy.service /etc/systemd/system/privoxy.service.dpkg-new
else
    echo "Installing default privoxy.service..."
    cp /usr/share/torcontroller/defaults/privoxy.service /etc/systemd/system/privoxy.service
fi

if [ -f /etc/systemd/system/tor.service ]; then
    echo "User-defined tor service found. Leaving existing file untouched."
    echo "A new version of the configuration file is available: /etc/systemd/system/tor.service.dpkg-new"
    echo "Please review and merge it into your existing configuration if necessary."
    cp /usr/share/torcontroller/defaults/tor.service /etc/systemd/system/tor.service.dpkg-new
else
    echo "Installing default tor.service..."
    cp /usr/share/torcontroller/defaults/tor.service /etc/systemd/system/tor.service
fi

if [ -f /etc/tor/torrc ]; then 
    echo "User-defined torrc found. Leaving existing file untouched."
    echo "A new version of the configuration file is available: /etc/tor/torrc.dpkg-new"
    echo "Please review and merge it into your existing configuration if necessary."
    cp /usr/share/torcontroller/defaults/tor/torrc /etc/tor/torrc.dpkg-new
else
    cp /usr/share/torcontroller/defaults/tor/torrc /etc/tor/torrc
    /usr/bin/torcontroller newpassword
    echo "[INFO] Default Tor password has been set to a randomly generated value."
    echo "[INFO] Please use '/usr/bin/torcontroller newpassword <your-tor-newpassword>' to change it if needed."
fi

if [ -f /etc/privoxy/config ]; then
    echo "User-defined privoxy config found. Leaving existing file untouched."
    echo "A new version of the configuration file is available: /etc/privoxy/config.dpkg-new"
    echo "Please review and merge it into your existing configuration if necessary."
    cp /usr/share/torcontroller/defaults/privoxy/config /etc/privoxy/config.dpkg-new
else
    cp /usr/share/torcontroller/defaults/privoxy/config /etc/privoxy/config
fi

if [ -f /etc/sudoers.d/torcontroller ]; then
    echo "User-defined sudoers.d torcontroller found. Leaving existing file untouched."
    echo "A new version of the configuration file is available: /etc/sudoers.d/torcontroller.dpkg-new"
    echo "Please review and merge it into your existing configuration if necessary."
    cp /usr/share/torcontroller/defaults/sudoers.d/torcontroller /etc/sudoers.d/torcontroller.dpkg-new
else
    cp /usr/share/torcontroller/defaults/sudoers.d/torcontroller /etc/sudoers.d/torcontroller
    chmod 0440 /etc/sudoers.d/torcontroller
fi

if [ -f /etc/torcontroller/torcontroller.yml ]; then
    echo "User-defined torcontroller yaml found. Leaving existing file untouched."
    echo "A new version of the configuration file is available: /etc/torcontroller/torcontroller.yml.dpkg-new"
    echo "Please review and merge it into your existing configuration if necessary."
    cp /usr/share/torcontroller/defaults/torcontroller.yml /etc/torcontroller/torcontroller.yml.dpkg-new
else
    cp /usr/share/torcontroller/defaults/torcontroller.yml /etc/torcontroller/torcontroller.yml
fi

echo "postinst script finished."

#DEBHELPLER#
