#!/bin/sh
# Make sure tor and privoxy service already stopped.
supervisorResponse=$(supervisorctl status 2>&1)
case "$supervisorResponse" in
*"no such file"*)
    supervisord -c /etc/supervisor/supervisord.conf
    ;;
esac
torsuperResponse=$(supervisorctl status tor | grep "tor")
case "$torsuperResponse" in
*"RUNNING"*)
    supervisorctl stop tor
    ;;
*"STOPPED"*)
    kill $(pidof tor) || true
    echo "Tor already stopped."
    ;;
*)
    echo "Unknown tor program status!"
    ;;
esac

privoxysuperResponse=$(supervisorctl status privoxy | grep "privoxy")
case "$privoxysuperResponse" in
*"RUNNING"*)
    supervisorctl stop privoxy
    ;;
*"STOPPED"*)
    kill $(pidof privoxy) || true
    echo "Tor already stopped."
    ;;
*)
    echo "Unknown privoxy program status!"
    ;;
esac
# If torrc and privoxy backup file existed,
# replace it.
if [ ! -f /etc/tor/torrc.back ]; then
    cp /etc/tor/torrc.back /etc/tor/torrc
    rm -f /etc/tor/torrc.back
fi
if [ ! -f /etc/privoxy/config.back ]; then
    cp /etc/privoxy/config.back /etc/privoxy/config
    rm -f /etc/privoxy/config.back
fi
# If supervisor user setting backup file existed,
# replace it.
if [ ! -f /etc/supervisor/supervisord.conf.back ]; then
    cp /etc/supervisor/supervisord.conf.back /etc/supervisor/supervisord.conf.back
    rm -f cp /etc/supervisor/supervisord.conf.back
    supervisorctl reread
    supervisorctl update
fi
# remove any tmp files.
rm -rf /tmp/torcontoller
echo "postrm script fiinished."
