name: CI then Release

on:
  push:
    tags:
      - 'v*'  # Triggered when a hashtag is pushed

jobs:
  build-and-release:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-22.04

    steps:
    - name: Actions Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU for ARM
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Create .env file
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        ARCH: ${{ matrix.arch }}
      run: bash ./scripts/env.sh

    - name: Pull and run container for ${{ matrix.arch }}
      run: |
        docker run --rm \
        --platform linux/${{ matrix.arch }} \
        -v $GITHUB_WORKSPACE:/workspace \
        -w /workspace \
        --env-file .env \
        ghcr.io/seicrypto/torcontroller/torcontroller-build:dev \
        bash -c "/workspace/scripts/build_and_sign.sh"
    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automatic release of .deb package for ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload .deb file
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.deb_file }}
        asset_name: torcontroller_${{ github.ref_name }}_${{ matrix.arch }}.deb
        asset_content_type: application/octet-stream
