name: CI then Release

on:
  push:
    tags:
      - 'v*'  # Triggered when a hashtag is pushed

jobs:
  build-and-release:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-22.04

    steps:
    - name: Actions Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU for ARM
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Ensure script is executable
      run: |
        chmod +x ./scripts/build_and_sign.sh

    - name: Create private-key.asc
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" > private-key.asc

    - name: Create .env file
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        ARCH: ${{ matrix.arch }}
      run: |
        echo "GPG_PASSPHRASE=${GPG_PASSPHRASE}" > .env
        echo "GPG_PUBLIC_KEY=${GPG_PUBLIC_KEY}" >> .env
        echo "ARCH=${ARCH}" >> .env

    - name: Pull and run container for ${{ matrix.arch }}
      run: |
        docker run -i \
        --platform linux/${{ matrix.arch }} \
        -v $GITHUB_WORKSPACE:/workspace \
        -w /workspace \
        --env-file .env \
        --name torcontroller_build_${{ matrix.arch }} \
        ghcr.io/seicrypto/torcontroller/torcontroller-build:dev \
        bash -c "/workspace/scripts/build_and_sign.sh && tail -f /dev/null"

    - name: Load environment variables
      run: |
        docker cp torcontroller_build_${{ matrix.arch }}:/workspace/container_up_env $GITHUB_WORKSPACE/container_up_env
        cat /workspace/container_up_env >> $GITHUB_ENV

    - name: Copy .deb file from container
      run: |
        docker cp torcontroller_build_${{ matrix.arch }}:/${{ env.deb_file }} $GITHUB_WORKSPACE/${{ env.deb_file }}

    - name: Remove container
      run: |
        docker rm -f torcontroller_build_${{ matrix.arch }}:/${{ env.deb_file }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automatic release of .deb package for ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload .deb file
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/${{ env.deb_file }}
        asset_name: torcontroller_${{ github.ref_name }}_${{ matrix.arch }}.deb
        asset_content_type: application/octet-stream
