name: Torcontroller Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  run-test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/seicrypto/torcontroller/torcontroller-test-env:dev

    steps:
    - name: Actions Checkout
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.13'

    - name: Build for Test
      run: |
        GOARCH=$(uname -m | grep -q 'aarch64' && echo "arm64" || echo "amd64")
        GOOS=linux GOARCH=$GOARCH go build -o torcontroller

    - name: Run unit test
      run: go test -v ./...
